// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

import {Test} from "forge-std/Test.sol";
import {ERC20} from "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import {ERC20Permit, IERC20Permit} from "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol";
import {ECDSA} from "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import {MessageHashUtils} from "@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol";

/**
 * @title ERC20Permit Test Suite
 * @dev This test suite verifies the functionality of an ERC20 token with EIP-2612 permit functionality.
 * The permit function allows token approvals via signed messages (EIP-712) without requiring on-chain transactions by
 * the token owner.
 *
 * Contracts:
 * - MyToken: A custom ERC20 token that includes ERC20Permit, enabling off-chain approvals via signatures, which can
 * then be relayed on-chain to authorize transfers.
 *
 * - Signer: Simulates the behavior of an off-chain signer. It mimics an account generating EIP-712 signatures
 * (typically done offline or off-chain).
 *   This contract uses a private key (generated using Foundry’s utilities) to sign `permit` approvals,
 *     allowing the relayer or others to submit these signed messages on-chain.
 *   This reflects how, in real-world use, a user could sign a transaction off-chain and allow another party to submit
 * it,
 *     reducing the need for the user to spend gas.
 *
 * - Relayer: A contract that acts on behalf of the token owner, submitting the signed permit approval to the
 * blockchain.
 *     This allows a third party to execute `permit` using the signature generated by the `Signer`.
 *
 * - ERC20PermitTest: A suite of test cases using Foundry to verify different scenarios of the permit functionality,
 * such as:
 *   - Valid permit usage
 *   - Handling of invalid signatures (e.g., wrong spender)
 *   - Invalid nonce rejection (replay attacks)
 *   - Expired permit signatures
 *   These tests ensure the correct behavior of the permit functionality as outlined in EIP-2612.
 */
contract MyToken is ERC20Permit {
    constructor() ERC20("MyToken", "MTK") ERC20Permit("MyToken") {
        _mint(msg.sender, 1000 * 10 ** decimals());
    }
}

contract Signer is Test {
    address internal owner;
    uint256 internal ownerPrivateKey;

    constructor() {
        (owner, ownerPrivateKey) = makeAddrAndKey("Owner");
    }

    function signPermit(
        ERC20Permit token,
        address spender,
        uint256 value,
        uint256 deadline
    )
        public
        view
        returns (uint8 v, bytes32 r, bytes32 s)
    {
        uint256 nonce = token.nonces(owner);
        bytes32 domainSeparator = token.DOMAIN_SEPARATOR();

        // Compute the struct hash
        bytes32 structHash = keccak256(
            abi.encode(
                keccak256("Permit(address owner,address spender,uint256 value,uint256 nonce,uint256 deadline)"),
                owner,
                spender,
                value,
                nonce,
                deadline
            )
        );

        // Compute the digest
        bytes32 digest = MessageHashUtils.toTypedDataHash(domainSeparator, structHash);

        // Sign the digest
        return vm.sign(ownerPrivateKey, digest);
    }

    function ownerAddress() public view returns (address) {
        return owner;
    }
}

contract Relayer {
    function relayPermit(
        ERC20Permit token,
        address owner,
        address spender,
        uint256 value,
        uint256 deadline,
        uint8 v,
        bytes32 r,
        bytes32 s
    )
        external
    {
        token.permit(owner, spender, value, deadline, v, r, s);
    }
}

contract ERC20PermitTest is Test {
    MyToken internal token;
    Signer internal signer;
    address internal signerOwnerAddress;
    address internal spender;
    Relayer internal relayer;

    function setUp() public {
        // Set up accounts
        spender = makeAddr("Spender");

        // Deploy token and signer
        token = new MyToken();
        signer = new Signer();
        signerOwnerAddress = signer.ownerAddress();

        // Transfer tokens to owner
        token.transfer(signerOwnerAddress, 100 * 10 ** token.decimals());

        // Deploy relayer
        relayer = new Relayer();
    }

    function testPermitViaRelayer() public {
        // Check allowance
        uint256 allowance = token.allowance(signerOwnerAddress, spender);
        assertEq(allowance, 0, "Allowance should be zero");

        uint256 value = 50 * 10 ** token.decimals();
        uint256 deadline = block.timestamp + 1 days;

        // Get signature from signer
        (uint8 v, bytes32 r, bytes32 s) = signer.signPermit(token, spender, value, deadline);

        // Relayer calls permit on behalf of the owner
        relayer.relayPermit(token, signerOwnerAddress, spender, value, deadline, v, r, s);

        // Check allowance
        allowance = token.allowance(signerOwnerAddress, spender);
        assertEq(allowance, value, "Allowance should be set via permit");
    }

    function testPermitInvalidSignature() public {
        uint256 value = 50 * 10 ** token.decimals();
        uint256 deadline = block.timestamp + 1 days;

        // Intentionally use the wrong spender to get an invalid signature
        address wrongSpender = makeAddr("WrongSpender");
        (uint8 v, bytes32 r, bytes32 s) = signer.signPermit(token, wrongSpender, value, deadline);

        // Attempt to relay the permit with invalid signature
        vm.expectPartialRevert(ERC20Permit.ERC2612InvalidSigner.selector);
        relayer.relayPermit(token, signerOwnerAddress, spender, value, deadline, v, r, s);
    }

    function testPermitExpired() public {
        uint256 value = 50 * 10 ** token.decimals();

        uint256 futureTimestamp = block.timestamp + 100 days;
        vm.warp(futureTimestamp); // move block.timestamp into the future

        // Set deadline to a timestamp in the past (e.g., 1 day ago from the current block time)
        uint256 permitDeadline = futureTimestamp - 10 days;
        uint256 missedDeadline = futureTimestamp - 1 days;

        // Get signature from signer (using the future deadline for signature creation)
        (uint8 v, bytes32 r, bytes32 s) = signer.signPermit(token, spender, value, permitDeadline);

        // Now simulate using the past deadline when relaying
        vm.expectPartialRevert(ERC20Permit.ERC2612ExpiredSignature.selector);
        relayer.relayPermit(token, signerOwnerAddress, spender, value, missedDeadline, v, r, s);
    }

    function testPermitInvalidNonce() public {
        uint256 value = 50 * 10 ** token.decimals();
        uint256 deadline = block.timestamp + 1 days;

        uint256 currentNonce = token.nonces(signerOwnerAddress);
        assertEq(currentNonce, 0, "Nonce should be zero at the beginning");

        (uint8 v, bytes32 r, bytes32 s) = signer.signPermit(token, spender, value, deadline);

        // Relayer calls permit on behalf of the owner (valid permit with nonce 0)
        relayer.relayPermit(token, signerOwnerAddress, spender, value, deadline, v, r, s);

        // Check that the nonce for the signer is now 1 (it should have incremented)
        currentNonce = token.nonces(signerOwnerAddress);
        assertEq(currentNonce, 1, "Nonce should have incremented after permit");

        // Attempt to use the same signature again (this should fail because the nonce is now 1, not 0)
        vm.expectPartialRevert(ERC20Permit.ERC2612InvalidSigner.selector);
        relayer.relayPermit(token, signerOwnerAddress, spender, value, deadline, v, r, s); // Using the same (v, r, s)

        // nonce did not change
        currentNonce = token.nonces(signerOwnerAddress);
        assertEq(currentNonce, 1, "Nonce did not change after rejected permit call");

        // Sign a new permit with the correct nonce (which is now 1)
        (v, r, s) = signer.signPermit(token, spender, value, deadline);

        // Try to relay again with the correct nonce (should succeed this time)
        relayer.relayPermit(token, signerOwnerAddress, spender, value, deadline, v, r, s);

        // Check that the nonce has incremented to 2
        currentNonce = token.nonces(signerOwnerAddress);
        assertEq(currentNonce, 2, "Nonce should have incremented to 2 after second permit");
    }
}
